[package]
name = "generic-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = { version = "1.5.0", features = ["derive"] }
wincode = { version = "0.4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
